char	*sys_errlist[] {
	&quot;Error 0&quot;,
	&quot;Not super-user&quot;,
	&quot;No such file or directory&quot;,
	&quot;No such process&quot;,
	&quot;Interrupted system call&quot;,
	&quot;I/O error&quot;,
	&quot;No such device or address&quot;,
	&quot;Arg list too long&quot;,
	&quot;Exec format error&quot;,
	&quot;Bad file number&quot;,
	&quot;No children&quot;,
	&quot;No more processes&quot;,
	&quot;Not enough core&quot;,
	&quot;Permission denied&quot;,
	&quot;Error 14&quot;,
	&quot;Block device required&quot;,
	&quot;Mount device busy&quot;,
	&quot;File exists&quot;,
	&quot;Cross-device link&quot;,
	&quot;No such device&quot;,
	&quot;Not a directory&quot;,
	&quot;Is a directory&quot;,
	&quot;Invalid argument&quot;,
	&quot;File table overflow&quot;,
	&quot;Too many open files&quot;,
	&quot;Not a typewriter&quot;,
	&quot;Text file busy&quot;,
	&quot;File too large&quot;,
	&quot;No space left on device&quot;,
	&quot;Illegal seek&quot;,
	&quot;Read-only file system&quot;,
	&quot;Too many links&quot;,
	&quot;Broken Pipe&quot;,
};
int	sys_nerr { sizeof sys_errlist/sizeof sys_errlist[0] };
